### ISSUE TITLE
fix warning in repentanceapi.lua

### ISSUE THREAD

**Issue by Zamiell** [filloax/isaac-api-autocomplete-lua#7]
```lua
---@param Entity Entity
---@return EntityRef
function EntityRef(Entity)

end
```

![image](https://user-images.githubusercontent.com/5511220/188280906-efe88f82-9922-46dc-9d2a-24ac3cd48928.png)

This causes errors even when only end-user source code files are open, so it needs to be fixed.

**Comment by filloax** [comment]
Fixed on the VSCode extension side
